---
title: "Gene set enrichment"
output: html_document
date: '2022-09-28'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(clusterProfiler)
library(org.Mm.eg.db)
library(Seurat)
library(dplyr)
library(ggplot2)
library(ReactomePA)
library(forcats)
library(DOSE)
library(pathview)

dir <- "Results/gene set enrichment/IRF8"
dir.create(dir)


mac <- readRDS("Results/2.3Int_all/all_data.RDS")
DefaultAssay(mac) <- "RNA"
mac <- NormalizeData(mac, normalization.method = "LogNormalize")
mac.IRF8 <- subset(x=mac,subset=Experiment2=="IRF8ko")

cl0.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 0, logfc.threshold = 0.25)
cl1.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 1, logfc.threshold = 0.25)
cl2.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 2, logfc.threshold = 0.25)
cl3.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 3, logfc.threshold = 0.25)
cl4.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 4, logfc.threshold = 0.25)
cl5.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 5, logfc.threshold = 0.25)
cl6.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 6, logfc.threshold = 0.25)
cl7.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 7, logfc.threshold = 0.25)
cl8.IRF8.markers <- FindMarkers(mac.IRF8, ident.1 = 8, logfc.threshold = 0.25)
```

```{r}
saveRDS(cl0.IRF8.markers, paste0(dir,"/IRF8.cl0.RDS"))
saveRDS(cl1.IRF8.markers, paste0(dir,"/IRF8.cl1.RDS"))
saveRDS(cl2.IRF8.markers, paste0(dir,"/IRF8.cl2.RDS"))
saveRDS(cl3.IRF8.markers, paste0(dir,"/IRF8.cl3.RDS"))
saveRDS(cl4.IRF8.markers, paste0(dir,"/IRF8.cl4.RDS"))
saveRDS(cl5.IRF8.markers, paste0(dir,"/IRF8.cl5.RDS"))
saveRDS(cl6.IRF8.markers, paste0(dir,"/IRF8.cl6.RDS"))
saveRDS(cl7.IRF8.markers, paste0(dir,"/IRF8.cl7.RDS"))
saveRDS(cl8.IRF8.markers, paste0(dir,"/IRF8.cl8.RDS"))

cl0.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl0.RDS")
cl1.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl1.RDS")
cl2.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl2.RDS")
cl3.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl3.RDS")
cl4.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl4.RDS")
cl5.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl5.RDS")
cl6.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl6.RDS")
cl7.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl7.RDS")
cl8.IRF8.markers <- readRDS("Results/gene set enrichment/IRF8/IRF8.cl8.RDS")

```


```{r}
#cluster 0
eg = bitr(rownames(cl0.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl0 <- merge(cl0.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl0) <- diffexpgenes.cl0$Row.names
diffexpgenes.cl0$Row.names <- NULL

fc <- diffexpgenes.cl0$avg_log2FC
names(fc) <- diffexpgenes.cl0$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse0 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse0@result

?gseGO

dotplot(gse0, showCategory=30, split=".sign", font=8, title="IRF8 Cluster 0") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl0.png"), height=9, width=5, dpi=600)

GO0 <- gse0@result$Description
head(GO0, 100)
write.csv2(gse0, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster0.csv")

dotplot(gse0, showCategory=c("MHC class II protein complex assembly", "macroautophagy", "regulation of chemokine production", "cytokine production involved in immune response", "regulation of fibroblast proliferation", "regulation of leukocyte chemotaxis"), split=".sign", font=14, title="IRF8 - Cluster 0") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))
ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl0.png"), height=4, width=7, dpi=600)
```


```{r setup, include=FALSE}
#cluster1
eg = bitr(rownames(cl1.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl1 <- merge(cl1.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl1) <- diffexpgenes.cl1$Row.names
diffexpgenes.cl1$Row.names <- NULL

fc <- diffexpgenes.cl1$avg_log2FC
names(fc) <- diffexpgenes.cl1$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse1 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse1@result

dotplot(gse1, showCategory=30, split=".sign", font=7, title="IRF8 Cluster 1") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl1.png"), height=4, width=8, dpi=600)

GO1 <- gse1@result$Description
head(GO1, 100)
write.csv2(gse1, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster1.csv")

dotplot(gse1, showCategory=c("response to tumor necrosis factor", "locomotion", "cell-cell fusion", "regulation of immune response", "immune response", "cytokine production"), split=".sign", font=14, title="IRF8 - Cluster 1") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))
ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl1.png"), height=3.5, width=7, dpi=600)
```


```{r}
#cluster 2
eg = bitr(rownames(cl2.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl2 <- merge(cl2.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl2) <- diffexpgenes.cl2$Row.names
diffexpgenes.cl2$Row.names <- NULL

fc <- diffexpgenes.cl2$avg_log2FC
names(fc) <- diffexpgenes.cl2$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse2 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse2@result

dotplot(gse2, showCategory=30, split=".sign", font=8, title="IRF8 Cluster 2") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl2.png"), height=9, width=5, dpi=600)

GO2 <- gse2@result$Description
head(GO2, 100)
write.csv2(gse2, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster2.csv")

?dotplot

dotplot(gse2, showCategory=c("fever generation", "acute inflammatory response", "cellular response to lipopolysaccharide", "chronic inflammatory response", "toll-like receptor signaling pathway", "chemokine-mediated signaling pathway"), split=".sign", font=14, title="IRF8 - Cluster 2") + facet_grid(.~.sign) + scale_colour_gradientn(colours = c("red4", "cornflowerblue"))

ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl2.png"), height=3.5, width=7, dpi=600)
```


```{r}
#cluster 3
eg = bitr(rownames(cl3.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl3 <- merge(cl3.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl3) <- diffexpgenes.cl3$Row.names
diffexpgenes.cl3$Row.names <- NULL

fc <- diffexpgenes.cl3$avg_log2FC
names(fc) <- diffexpgenes.cl3$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse3 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse3@result

dotplot(gse3, showCategory=30, split=".sign", font=7, title="IRF8 Cluster 3") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl3.png"), height=4, width=8, dpi=600)

GO3 <- gse3@result$Description
head(GO3, 200)
write.csv2(gse3, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster3.csv")

dotplot(gse3, showCategory=c("antigen processing and presentation of peptide antigen", "MHC protein complex assembly", "prostaglandin biosynthetic process", "unsaturated fatty acid biosynthetic process", "T-helper 1 type immune response", "positive regulation of acute inflammatory response", "cytokine production involved in immune response"), split=".sign", font=14, title="IRF8 - Cluster 3") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))
ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl3.png"), height=4, width=7, dpi=600)
```


```{r}
#cluster 4
eg = bitr(rownames(cl4.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl4 <- merge(cl4.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl4) <- diffexpgenes.cl4$Row.names
diffexpgenes.cl4$Row.names <- NULL

fc <- diffexpgenes.cl4$avg_log2FC
names(fc) <- diffexpgenes.cl4$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse4 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse4@result

dotplot(gse4, showCategory=30, split=".sign", font=7, title="IRF8 Cluster 4") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl4.png"), height=4, width=8, dpi=600)

GO4 <- gse4@result$Description
head(GO4, 200)
write.csv2(gse4, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster4.csv")


dotplot(gse4, showCategory=c("phagocytosis, recognition", "complement activation, classical pathway", "skeletal muscle cell differentiation",  "defense response to Gram-negative bacterium", "cartilage development", "connective tissue development"), split=".sign", font=14, title="IRF8 - Cluster 4") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))
ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl4.png"), height=3.5, width=7, dpi=600)
```


```{r}
#cluster 6
eg = bitr(rownames(cl6.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl6 <- merge(cl6.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl6) <- diffexpgenes.cl6$Row.names
diffexpgenes.cl6$Row.names <- NULL

fc <- diffexpgenes.cl6$avg_log2FC
names(fc) <- diffexpgenes.cl6$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse6 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse6@result

dotplot(gse6, showCategory=30, split=".sign", font=5, title="IRF8 - Mc-like") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl6.png"), height=9, width=5, dpi=600)

GO6 <- gse6@result$Description
head(GO6, 100)
write.csv2(gse6, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster6.csv")


dotplot(gse6, showCategory=c("MHC class II protein complex assembly", "response to type I interferon", "angiogenesis", "wound healing", "regulation of prostaglandin biosynthetic process", "T-helper 1 type immune response", "positive chemotaxis", "respiratory burst"), split=".sign", font=14, title="IRF8 - Cluster 6") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))
ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl6.png"), height=4, width=7, dpi=600)
```

```{r}
#cluster 7
eg = bitr(rownames(cl7.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl7 <- merge(cl7.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl7) <- diffexpgenes.cl7$Row.names
diffexpgenes.cl7$Row.names <- NULL

fc <- diffexpgenes.cl7$avg_log2FC
names(fc) <- diffexpgenes.cl7$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse7 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse7@result

dotplot(gse7, showCategory=30, split=".sign", font=5, title="IRF8 Cluster 7") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl7.png"), height=9, width=5, dpi=600)

GO7 <- gse7@result$Description
head(GO7, 100)
write.csv2(gse7, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster7.csv")


dotplot(gse7, showCategory=c("antigen processing and presentation","adaptive immune response", "chemokine-mediated signaling pathway", "innate immune response", "angiogenesis","wound healing", "response to tumor necrosis factor", "immune system process", "leukocyte mediated immunity"), split=".sign", font=16, title="IRF8 - Cluster 7") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))
ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl7.png"), height=4, width=8, dpi=600)
```

```{r}
#cluster 8
eg = bitr(rownames(cl8.IRF8.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl8 <- merge(cl8.IRF8.markers, eg, by = "row.names")
rownames(diffexpgenes.cl8) <- diffexpgenes.cl8$Row.names
diffexpgenes.cl8$Row.names <- NULL

fc <- diffexpgenes.cl8$avg_log2FC
names(fc) <- diffexpgenes.cl8$ENTREZID
fc <- sort(fc, decreasing = T)
y <- gsePathway(fc,organism = "mouse")
res <- as.data.frame(y)
res <- res[order(res$NES, decreasing = T),]

gse8 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db")
res <- gse8@result

dotplot(gse8, showCategory=30, split=".sign", font=5, title="IRF8 Cluster 8") + facet_grid(.~.sign)
ggsave(paste0(dir,"/IRF8.GSEAdot.cl8.png"), height=9, width=5, dpi=600)

GO8 <- gse8@result$Description
head(GO8, 100)
write.csv2(gse8, "Results/gene set enrichment/IRF8/IRF8-gse/IRF8-gse-cluster8.csv")


dotplot(gse8, showCategory=c("antigen processing and presentation","adaptive immune response", "chemokine-mediated signaling pathway", "innate immune response", "angiogenesis","wound healing", "response to tumor necrosis factor", "immune system process", "leukocyte mediated immunity"), split=".sign", font=16, title="IRF8 - Cluster 8") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))
ggsave(paste0(dir,"/IRF8.GSEAdot.select.cl8.png"), height=4, width=8, dpi=600)
```






