---
title: "Gene set enrichment"
output: html_document
date: '2022-09-28'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(clusterProfiler)
library(org.Mm.eg.db)
library(Seurat)
library(tidyverse)
library(cowplot)
library(patchwork)

dir <- "Results/gene set enrichment/WT"
dir.create(dir)

#mac <- readRDS("Results/2.3Int_all/all_data.RDS")
#DefaultAssay(mac) <- "RNA"
#mac <- NormalizeData(mac, normalization.method = "LogNormalize")
#mac.wt <- subset(x=mac,subset=Experiment2=="WT")


#cl0.wt.markers <- FindMarkers(mac.wt, ident.1 = 0, logfc.threshold = 0.25)
#cl1.wt.markers <- FindMarkers(mac.wt, ident.1 = 1, logfc.threshold = 0.25)
#cl2.wt.markers <- FindMarkers(mac.wt, ident.1 = 2, logfc.threshold = 0.25)
#cl3.wt.markers <- FindMarkers(mac.wt, ident.1 = 3, logfc.threshold = 0.25)
#cl4.wt.markers <- FindMarkers(mac.wt, ident.1 = 4, logfc.threshold = 0.25)
#cl5.wt.markers <- FindMarkers(mac.wt, ident.1 = 5, logfc.threshold = 0.25)
#cl6.wt.markers <- FindMarkers(mac.wt, ident.1 = 6, logfc.threshold = 0.25)
#cl7.wt.markers <- FindMarkers(mac.wt, ident.1 = 7, logfc.threshold = 0.25)
#cl8.wt.markers <- FindMarkers(mac.wt, ident.1 = 8, logfc.threshold = 0.25)

```

```{r}
#saveRDS(cl0.wt.markers, paste0(dir,"/cl0.RDS"))
#saveRDS(cl01.wt.markers, paste0(dir,"/cl01.RDS"))
#saveRDS(cl1.wt.markers, paste0(dir,"/cl1.RDS"))
#saveRDS(cl2.wt.markers, paste0(dir,"/cl2.RDS"))
#saveRDS(cl3.wt.markers, paste0(dir,"/cl3.RDS"))
#saveRDS(cl4.wt.markers, paste0(dir,"/cl4.RDS"))
#saveRDS(cl5.wt.markers, paste0(dir,"/cl5.RDS"))
#saveRDS(cl6.wt.markers, paste0(dir,"/cl6.RDS"))
#saveRDS(cl7.wt.markers, paste0(dir,"/cl7.RDS"))
#saveRDS(cl8.wt.markers, paste0(dir,"/cl8.RDS"))

cl0.wt.markers <- readRDS("Results/gene set enrichment/WT/cl0.RDS")
cl1.wt.markers <- readRDS("Results/gene set enrichment/WT/cl1.RDS")
cl2.wt.markers <- readRDS("Results/gene set enrichment/WT/cl2.RDS")
cl3.wt.markers <- readRDS("Results/gene set enrichment/WT/cl3.RDS")
cl4.wt.markers <- readRDS("Results/gene set enrichment/WT/cl4.RDS")
cl5.wt.markers <- readRDS("Results/gene set enrichment/WT/cl5.RDS")
cl6.wt.markers <- readRDS("Results/gene set enrichment/WT/cl6.RDS")
cl7.wt.markers <- readRDS("Results/gene set enrichment/WT/cl7.RDS")
cl8.wt.markers <- readRDS("Results/gene set enrichment/WT/cl8.RDS")

```


```{r}
#cluster 0
eg = bitr(rownames(cl0.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl0 <- merge(cl0.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl0) <- diffexpgenes.cl0$Row.names
diffexpgenes.cl0$Row.names <- NULL

fc <- diffexpgenes.cl0$avg_log2FC
names(fc) <- diffexpgenes.cl0$ENTREZID
fc <- sort(fc, decreasing = T)

gse0 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse0@result

dotplot(gse0, showCategory=30, split=".sign", font=8, title="WT Cluster 0") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl0.png"), height=9, width=5, dpi=600)

GO0 <- gse0@result$Description
head(GO0, 100)
write.csv2(gse0, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster0.csv")

g0<-dotplot(gse0, showCategory=c(
 "proteasome-mediated ubiquitin-dependent protein catabolic process",
 "prostaglandin metabolic process",
  "production of molecular mediator of immune response",
 "MHC class II protein complex assembly", 
  "response to interferon-gamma",
  "cytokine production involved in immune response"), split=".sign", font=14, title= "0 - Homeostatic A") +facet_grid(.~.sign) +scale_colour_gradientn(colours = c("red4", "cornflowerblue")) +theme(plot.title= element_text(size=20, colour = "#8AB6F9")) 

ggsave(paste0(dir,"/wt.GSEAdot.select.cl0.png"), height=4, width=6.6, dpi=600)
```


```{r setup, include=FALSE}
#cluster1
eg = bitr(rownames(cl1.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl1 <- merge(cl1.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl1) <- diffexpgenes.cl1$Row.names
diffexpgenes.cl1$Row.names <- NULL

fc <- diffexpgenes.cl1$avg_log2FC
names(fc) <- diffexpgenes.cl1$ENTREZID
fc <- sort(fc, decreasing = T)

gse1 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse1@result

dotplot(gse1, showCategory=30, split=".sign", font=7, title="WT Cluster 1") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl1.png"), height=4, width=8, dpi=600)

GO1 <- gse1@result$Description
head(GO1, 100)
write.csv2(gse1, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster1.csv")

g1<- dotplot(gse1, showCategory=c("cell-cell adhesion", "antigen processing and presentation of exogenous antigen", "cell activation", "immune system process"), split=".sign", font=14, title= "1 - Homeostatic B") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=20, colour = "#B25690"))
ggsave(paste0(dir,"/wt.GSEAdot.select.cl1.png"), height=4, width=6.6, dpi=600)
```

```{r}
#cluster 2
eg = bitr(rownames(cl2.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl2 <- merge(cl2.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl2) <- diffexpgenes.cl2$Row.names
diffexpgenes.cl2$Row.names <- NULL

fc <- diffexpgenes.cl2$avg_log2FC
names(fc) <- diffexpgenes.cl2$ENTREZID
fc <- sort(fc, decreasing = T)

gse2 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse2@result

dotplot(gse2, showCategory=30, split=".sign", font=8, title="WT Cluster 2") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl2.png"), height=9, width=5, dpi=600)

GO2 <- gse2@result$Description
head(GO2, 100)
write.csv2(gse2, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster2.csv")

g2<- dotplot(gse2, showCategory=c("fever generation", 
                             "acute inflammatory response", 
                             "cellular response to lipopolysaccharide", 
                             "acute-phase response", 
                             "toll-like receptor signaling pathway", 
                             "chemokine-mediated signaling pathway"), split=".sign", font=14, title= "2 - Innate inflammatory") + facet_grid(.~.sign) + scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=20, colour = "#ffc13b"))
g2
ggsave(paste0(dir,"/wt.GSEAdot.select.cl2.png"), height=4, width=6.6, dpi=600)
```


```{r}
#cluster 3
eg = bitr(rownames(cl3.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl3 <- merge(cl3.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl3) <- diffexpgenes.cl3$Row.names
diffexpgenes.cl3$Row.names <- NULL

fc <- diffexpgenes.cl3$avg_log2FC
names(fc) <- diffexpgenes.cl3$ENTREZID
fc <- sort(fc, decreasing = T)

gse3 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse3@result

dotplot(gse3, showCategory=30, split=".sign", font=7, title= "3 - Inflammatory adaptive") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl3.png"), height=4, width=8, dpi=600)

GO3 <- gse3@result$Description
head(GO3, 200)
write.csv2(gse3, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster3.csv")

g3<- dotplot(gse3, showCategory=c("antigen processing and presentation of peptide antigen", 
                             "MHC protein complex assembly", 
                             "adaptive immune response", 
                             "unsaturated fatty acid biosynthetic process", 
                             "positive regulation of T cell activation",
                             "response to interferon-gamma"), split=".sign", font=14, title= "3 - Adaptive inflammatory") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue")) +theme(plot.title= element_text(size=20, colour = "#04d4f0"))
g3
ggsave(paste0(dir,"/wt.GSEAdot.select.cl3.png"), height=4, width=6.6, dpi=600)
```


```{r}
#cluster 4
eg = bitr(rownames(cl4.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl4 <- merge(cl4.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl4) <- diffexpgenes.cl4$Row.names
diffexpgenes.cl4$Row.names <- NULL

fc <- diffexpgenes.cl4$avg_log2FC
names(fc) <- diffexpgenes.cl4$ENTREZID
fc <- sort(fc, decreasing = T)

gse4 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse4@result

dotplot(gse4, showCategory=30, split=".sign", font=7, title="WT Cluster 4") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl4.png"), height=4, width=8, dpi=600)

GO4 <- gse4@result$Description
head(GO4, 200)
write.csv2(gse4, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster4.csv")

g4<- dotplot(gse4, showCategory=c("phagocytosis, recognition", 
                             "complement activation, classical pathway", 
                             "skeletal muscle cell differentiation",
                             "chondrocyte differentiation",
                             "muscle tissue development",
                             "aerobic respiration"), split=".sign", font=14, title= "4 - Regulatory") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=20, colour = "#5c3c92"))
g4
ggsave(paste0(dir,"/wt.GSEAdot.select.cl4.png"), height=4, width=6.6, dpi=600)
```



```{r}
#cluster 5
eg = bitr(rownames(cl5.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl5 <- merge(cl5.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl5) <- diffexpgenes.cl5$Row.names
diffexpgenes.cl5$Row.names <- NULL

fc <- diffexpgenes.cl5$avg_log2FC
names(fc) <- diffexpgenes.cl5$ENTREZID
fc <- sort(fc, decreasing = T)

gse5 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=67)
res <- gse5@result

dotplot(gse5, showCategory=30, split=".sign", font=8, title="WT Cluster 5") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl5.png"), height=12, width=12, dpi=600)

GO5 <- gse5@result$Description
head(GO5, 100)
write.csv2(gse5, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster5.csv")


g5 <- dotplot(gse5, showCategory=c("immune system process", 
                             "bone resorption", 
                             "bone remodeling", 
                             "tissue remodeling"), split=".sign", font=14, title= "5 - tissue-shaping") + facet_grid(.~.sign)+scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=20, colour = "#077b8a"))
g5
ggsave(paste0(dir,"/wt.GSEAdot.select.cl5.png"), height=3.2, width=6.6, dpi=600)
```



```{r}
#cluster 6
eg = bitr(rownames(cl6.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl6 <- merge(cl6.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl6) <- diffexpgenes.cl6$Row.names
diffexpgenes.cl6$Row.names <- NULL

fc <- diffexpgenes.cl6$avg_log2FC
names(fc) <- diffexpgenes.cl6$ENTREZID
fc <- sort(fc, decreasing = T)


gse6 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse6@result

dotplot(gse6, showCategory=30, split=".sign", font=5, title="WT - Mc-like") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl6.png"), height=9, width=5, dpi=600)

GO6 <- gse6@result$Description
head(GO6, 100)
write.csv2(gse6, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster6.csv")


g6<- dotplot(gse6, showCategory=c("antigen processing and presentation of exogenous antigen", "response to type I interferon", 
"angiogenesis", 
"wound healing", 
"phagocytosis, engulfment",
"defense response to virus",
"regulation of innate immune response"), split=".sign", font=14, title= "6 - Monocyte-like") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=20, colour = "#d72631"))
g6
ggsave(paste0(dir,"/wt.GSEAdot.select.cl6.png"), height=4.4, width=6.6, dpi=600)
```

```{r}
#cluster 7
eg = bitr(rownames(cl7.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl7 <- merge(cl7.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl7) <- diffexpgenes.cl7$Row.names
diffexpgenes.cl7$Row.names <- NULL

fc <- diffexpgenes.cl7$avg_log2FC
names(fc) <- diffexpgenes.cl7$ENTREZID
fc <- sort(fc, decreasing = T)


gse7 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse7@result

dotplot(gse7, showCategory=30, split=".sign", font=5, title="WT Cluster 7") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl7.png"), height=9, width=5, dpi=600)

GO7 <- gse7@result$Description
head(GO7, 100)
write.csv2(gse7, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster7.csv")


g7<- dotplot(gse7, showCategory=c("antigen processing and presentation",
                             "monocyte chemotaxis",
                             "response to virus",
                             "cell adhesion",
                             "regulation of viral genome replication", "response to tumor necrosis factor"), split=".sign", font=14, title= "7 - Recruiting") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=20, colour = "#c38b72"))
g7
ggsave(paste0(dir,"/wt.GSEAdot.select.cl7.png"), height=4, width=6.6, dpi=600)
```

```{r}
#cluster 8
eg = bitr(rownames(cl8.wt.markers), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl8 <- merge(cl8.wt.markers, eg, by = "row.names")
rownames(diffexpgenes.cl8) <- diffexpgenes.cl8$Row.names
diffexpgenes.cl8$Row.names <- NULL

fc <- diffexpgenes.cl8$avg_log2FC
names(fc) <- diffexpgenes.cl8$ENTREZID
fc <- sort(fc, decreasing = T)

gse8 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse8@result

dotplot(gse8, showCategory=30, split=".sign", font=5, title="WT Cluster 8") + facet_grid(.~.sign)
ggsave(paste0(dir,"/wt.GSEAdot.cl8.png"), height=9, width=5, dpi=600)

GO8 <- gse8@result$Description
head(GO8, 100)
write.csv2(gse8, "Results/gene set enrichment/WT/WT-gse/WT-gse-cluster8.csv")


g8<- dotplot(gse8, showCategory=c("cell adhesion mediated by integrin",
                             "glial cell migration",
                             "gliogenesis",
                             "actin cytoskeleton organization",
                             "locomotion",
                             "response to molecule of bacterial origin"), split=".sign", font=14, title= "8 - sNaM") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=20, colour = "#80c904"))
g8
ggsave(paste0(dir,"/wt.GSEAdot.select.cl8.png"), height=4, width=6.6, dpi=600)
```


```{r}
g0+g1+g2+g3+g4+g5+g6+g7+g8+plot_layout(ncol = 3)
ggsave(paste0(dir,"/wt.allGO.png"), height=12, width=22, dpi=600)

```




