---
title: "grouped expression"
output: html_document
date: '2022-06-07'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(Seurat)
library(ggplot2)
library(readxl)
library(tidyverse)
library(RColorBrewer)
library(patchwork)
library(ggpubr)

dir <- "Results/Gene_expressions/grouped_expressions"
dir.create(dir)

mac <- readRDS("Results/2.3Int_all/all_data.RDS")
DefaultAssay(mac) <- "RNA"
mac<- NormalizeData(mac, normalization.method = "LogNormalize")
total.gene.list <- rownames(x=mac)


#inflammasome
inflammasome.list <- read_xlsx("gene_lists/inflammasome.xlsx")
inflammasome.genes <- inflammasome.list$Symbol
inflammasome <- intersect(total.gene.list, inflammasome.genes)
list(inflammasome)

# Get mean expression of genes of interest per cell
agg.inflammasome <- colSums(x = mac@assays$RNA@data[inflammasome, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$inflammasome.score'
if (all(names(x = agg.inflammasome) == rownames(x = mac@meta.data))) {
  mac@meta.data$Inflammasome <- agg.inflammasome
}


# Plot mean expression using Seurat::FeaturePlot()
Inflammasome <- FeaturePlot(mac, order=T, features= "Inflammasome", min.cutoff='q5', max.cutoff='q95', pt.size = 0.8, split.by = "Experiment2", combine=T, label=F) +theme(legend.position = "right") +scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))
Inflammasome [[1]] <- Inflammasome[[1]]+scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))
Inflammasome
 

#tissue
tissue.list <- read_xlsx("gene_lists/Tissue_remodeling.xlsx")
tissue.genes <- tissue.list$Symbol
Tissue_remodeling <- intersect(total.gene.list, tissue.genes)
list(Tissue_remodeling)

# Get mean expression of genes of interest per cell
agg.tissue <- colSums(x = mac@assays$RNA@data[Tissue_remodeling, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$inflammasome.score'
if (all(names(x = agg.tissue) == rownames(x = mac@meta.data))) {
  mac@meta.data$Tissue_remodeling <- agg.tissue
}


#phagocytosis
phagocytosis.list <- read_xlsx("gene_lists/Phagocytosis.xlsx")
phagocytosis.genes <- phagocytosis.list$Symbol
Phagocytosis <- intersect(total.gene.list, phagocytosis.genes)
list(Phagocytosis)

# Get mean expression of genes of interest per cell
agg.phagocytosis <- colSums(x = mac@assays$RNA@data[Phagocytosis, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$phagocytosis.score'
if (all(names(x = agg.phagocytosis) == rownames(x = mac@meta.data))) {
  mac@meta.data$Phagocytosis <- agg.phagocytosis
}


#ROS
ROS.list <- read_xlsx("gene_lists/ROS.xlsx")
ROS.genes <- ROS.list$Symbol
ROS <- intersect(total.gene.list, ROS.genes)
list(ROS)

# Get mean expression of genes of interest per cell
agg.ROS <- colSums(x = mac@assays$RNA@data[ROS, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$ROS.score'
if (all(names(x = agg.ROS) == rownames(x = mac@meta.data))) {
  mac@meta.data$ROS <- agg.ROS
}

#Antigen presentation
Antigen.list <- read_xlsx("gene_lists/Antigen_presentation.xlsx")
Antigen.genes <- Antigen.list$Symbol
Antigen_presentation <- intersect(total.gene.list, Antigen.genes)
list(Antigen_presentation)

# Get mean expression of genes of interest per cell
agg.Antigen_presentation <- colSums(x = mac@assays$RNA@data[Antigen_presentation, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$ROS.score'
if (all(names(x = agg.Antigen_presentation) == rownames(x = mac@meta.data))) {
  mac@meta.data$Antigen_presentation <- agg.Antigen_presentation
}


```

```{r}
#mac<- NormalizeData(mac, normalization.method = "LogNormalize")


p1<- VlnPlot(mac, split.by="Experiment2",split.plot=T, features="Antigen_presentation", idents=c(0,1,2,3,4,5,6,7,8), cols=c("cornflowerblue", "dark red"), pt.size = 0, sort="increasing", log=T)+labs(title="Antigen processing/presentation", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=18), axis.text=element_text(size=14), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=18, face="plain", vjust = 3))+geom_boxplot(width=.1, fill="white") +theme(legend.position="none")
ggsave(paste0(dir,"/Antigen_presentation.png"), height=3, width=5, dpi=600)

p2<- VlnPlot(mac, split.by="Experiment2",split.plot=T, features="ROS", idents=c(0,1,2,3,4,5,6,7,8), cols=c("cornflowerblue", "dark red"), pt.size = 0, sort="increasing", log=T)+labs(title="ROS", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=18), axis.text=element_text(size=14), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=18, face="plain", vjust = 3))+geom_boxplot(width=.1, fill="white") +theme(legend.position="none")
ggsave(paste0(dir,"/ROS.png"), height=3, width=5, dpi=600)

p3<- VlnPlot(mac, split.by="Experiment2",split.plot=T, features="Inflammasome", idents=c(0,1,2,3,4,5,6,7,8), cols=c("cornflowerblue", "dark red"), pt.size = 0, sort="increasing", log=T)+labs(title="Inflammasome", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=18), axis.text=element_text(size=14), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=18, face="plain", vjust = 3))+geom_boxplot(width=.1, fill="white") +theme(legend.position="none")
ggsave(paste0(dir,"/Inflammasome.png"), height=3, width=5, dpi=600)

p4<- VlnPlot(mac, split.by="Experiment2",split.plot=T, features="Phagocytosis", idents=c(0,1,2,3,4,5,6,7,8), cols=c("cornflowerblue", "dark red"), pt.size = 0, sort="increasing", log=T)+labs(title="Phagocytosis", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=18), axis.text=element_text(size=14), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=18, face="plain", vjust = 3))+geom_boxplot(width=.1, fill="white") +theme(legend.position="right")
ggsave(paste0(dir,"/Phagocytosis.png"), height=3, width=5, dpi=600)

p5<- VlnPlot(mac, split.by="Experiment2",split.plot=T, features="Tissue_remodeling", idents=c(0,1,2,3,4,5,6,7,8), cols=c("cornflowerblue", "dark red"), pt.size = 0, sort="increasing", log=T)+labs(title="Tissue remodeling", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=18), axis.text=element_text(size=14), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=18, face="plain", vjust = 3))+geom_boxplot(width=.1, fill="white") +theme(legend.position="none")
ggsave(paste0(dir,"/Tissue_remodeling.png"), height=3, width=5, dpi=600)

p1+p2+p3+p5+p4 + plot_layout(ncol = 2)
ggsave(paste0(dir,"/Vln-WT-irf-split.png"), height=9, width=10, dpi=600)


```





```{r}
mac.wt <- subset(x=mac,subset=Experiment2=="WT")

cols.antigen=c("#d72631","#04d4f0","#ffc13b","#B25690","#5c3c92","#077b8a","#c38b72","#80c904","#8AB6F9")

p1<- VlnPlot(mac.wt, features="Antigen_presentation", idents=c(0,1,2,3,4,5,6,7,8), cols=cols.antigen, pt.size = 0, sort="increasing", log=T)+labs(title="Antigen processing/presentation", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=20), axis.text=element_text(size=16), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=28, face="plain", vjust = 1))+geom_boxplot(width=.2, fill="white") +theme(legend.position="none")


cols.inflammasome=c("#ffc13b","#04d4f0","#d72631","#c38b72","#80c904", "#077b8a","#B25690","#8AB6F9","#5c3c92")

p2<- VlnPlot(mac.wt, features="Inflammasome", idents=c(0,1,2,3,4,5,6,7,8), cols=cols.inflammasome, pt.size = 0, sort="increasing", log=T)+labs(title="Inflammasome", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=20), axis.text=element_text(size=16), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=28, face="plain", vjust = 1))+geom_boxplot(width=.2, fill="white") +theme(legend.position="none")


cols.tissue=c("#077b8a", "#ffc13b","#d72631","#c38b72", "#B25690", "#80c904","#8AB6F9","#04d4f0","#5c3c92")

p3<- VlnPlot(mac.wt, features="Tissue_remodeling", idents=c(0,1,2,3,4,5,6,7,8), cols=cols.tissue, pt.size = 0, sort="increasing", log=T)+labs(title="Tissue remodeling", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=20), axis.text=element_text(size=16), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=28, face="plain", vjust = 1))+geom_boxplot(width=.2, fill="white") +theme(legend.position="none")

cols.phago=c("#d72631","#ffc13b","#077b8a","#80c904","#c38b72","#B25690", "#04d4f0","#8AB6F9", "#5c3c92")

p4<- VlnPlot(mac.wt, features="Phagocytosis", idents=c(0,1,2,3,4,5,6,7,8), cols=cols.phago, pt.size = 0, sort="increasing", log=T)+labs(title="Phagocytosis", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=20), axis.text=element_text(size=16), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=28, face="plain", vjust = 1))+geom_boxplot(width=.2, fill="white") +theme(legend.position="none")


p1<- p1+stat_compare_means(comparisons = list(c(1,4)), label = "p.signif")
p2<- p2+stat_compare_means(comparisons = list(c(2,7)), label = "p.signif")
p3<- p3+stat_compare_means(comparisons = list(c(1,4), c(6,9)), label = "p.signif")
p4<- p4+stat_compare_means(comparisons = list(c(1,3), c(5,9)), label = "p.signif")

p1+p2+p3+p4+ plot_layout(ncol = 2)
ggsave(paste0(dir,"/wt.Vln.png"), height=9.5, width=14, dpi=600)

```


```{r}
mac<- NormalizeData(mac, normalization.method = "LogNormalize")


#BM
BM.list <- read_xlsx("gene_lists/Res-BM.xlsx", sheet = "ranked up in BM")
BM.genes <- BM.list$Symbol
BM_mac <- intersect(total.gene.list, BM.genes)
list(BM_mac)


# Get mean expression of genes of interest per cell
agg.BM_mac <- colSums(x = mac@assays$RNA@data[BM_mac, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$ROS.score'
if (all(names(x = agg.BM_mac) == rownames(x = mac@meta.data))) {
  mac@meta.data$BM_mac <- agg.BM_mac
}

#Res
Res.list <- read_xlsx("gene_lists/Res-BM.xlsx", sheet = "ranked up in Res")
Res.genes <- Res.list$Symbol
Res_mac <- intersect(total.gene.list, Res.genes)
list(Res_mac)


# Get mean expression of genes of interest per cell
agg.Res_mac <- colSums(x = mac@assays$RNA@data[Res_mac, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$ROS.score'
if (all(names(x = agg.Res_mac) == rownames(x = mac@meta.data))) {
  mac@meta.data$Res_mac <- agg.Res_mac
}


mac.wt <- subset(x=mac,subset=Experiment2=="WT")

cols.BM=c("#d72631", "#04d4f0","#80c904", "#ffc13b", "#c38b72", "#077b8a",  "#B25690","#8AB6F9","#5c3c92")

p1<- VlnPlot(mac.wt, features="BM_mac", idents=c(0,1,2,3,4,5,6,7,8), cols=cols.BM, pt.size = 0, sort="increasing", log=T)+labs(title="Up in BM-mac", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=20), axis.text=element_text(size=16), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=20, face="plain", vjust = 1))+geom_boxplot(width=.3, fill="white") +theme(legend.position="none")

cols.Res=c("#077b8a","#c38b72","#B25690","#8AB6F9","#ffc13b","#5c3c92", "#04d4f0", "#80c904", "#d72631")

p2<- VlnPlot(mac.wt, features="Res_mac", idents=c(0,1,2,3,4,5,6,7,8), cols=cols.Res, pt.size = 0, sort="increasing", log=T)+labs(title="Up in Res-mac", x ="Cluster", y = "Aggregated count") +theme(text = element_text(size=20), axis.text=element_text(size=16), axis.text.x = element_text(angle = 0, hjust=0.5), plot.title = element_text(size=20, face="plain", vjust = 1))+geom_boxplot(width=.3, fill="white") +theme(legend.position="none")
p2

p1<- p1+stat_compare_means(comparisons = list(c(2,4), c(8,9)), label = "p.signif")
p2<- p2+stat_compare_means(comparisons = list(c(5,6), c(6,7)), label = "p.signif")
p1+p2+plot_layout(ncol = 2)
ggsave(paste0(dir,"/wt.BM-Res.png"), height=4.5, width=13, dpi=600)


```






