---
title: "WT-IRF8"
output: html_document
date: "2023-01-25"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(clusterProfiler)
library(org.Mm.eg.db)
library(Seurat)
library(tidyverse)
library(cowplot)

dir <- "Results/Comparison WT-IRF8"
dir.create(dir)

mac <- readRDS("Results/2.3Int_all/all_data.RDS")
DefaultAssay(mac) <- "RNA"
mac <- NormalizeData(mac, normalization.method = "LogNormalize")

mac$cluster.Experiment2 <- paste(Idents(mac), mac$Experiment2, sep = "_")
mac$cluster <- Idents(mac)
Idents(mac) <- "cluster.Experiment2"

cl0 <- FindMarkers(mac, ident.1 = "0_IRF8ko", ident.2 = "0_WT", logfc.threshold = 0.25)
cl01 <- FindMarkers(mac, ident.1= c("0_IRF8ko","1_IRF8ko"), ident.2 = c("0_WT", "1_WT"), logfc.threshold = 0.25)
cl1 <- FindMarkers(mac, ident.1 = "1_IRF8ko", ident.2 = "1_WT", logfc.threshold = 0.25)
cl2 <- FindMarkers(mac, ident.1 = "2_IRF8ko", ident.2 = "2_WT", logfc.threshold = 0.25)
cl3 <- FindMarkers(mac, ident.1 = "3_IRF8ko", ident.2 = "3_WT", logfc.threshold = 0.25)
cl4 <- FindMarkers(mac, ident.1 = "4_IRF8ko", ident.2 = "4_WT", logfc.threshold = 0.25)
cl5 <- FindMarkers(mac, ident.1 = "5_IRF8ko", ident.2 = "5_WT", logfc.threshold = 0.25)
cl6 <- FindMarkers(mac, ident.1 = "6_IRF8ko", ident.2 = "6_WT", logfc.threshold = 0.25)
cl7 <- FindMarkers(mac, ident.1 = "7_IRF8ko", ident.2 = "7_WT", logfc.threshold = 0.25)
cl8 <- FindMarkers(mac, ident.1 = "8_IRF8ko", ident.2 = "8_WT", logfc.threshold = 0.25)

```

```{r}
Idents(mac)<- mac$Experiment2
all <- FindMarkers(mac, ident.1="WT", ident.2="IRF8ko", only.pos=F)
write.xlsx(all, rowNames=T, paste0(dir,"/all.markers.xlsx"))

```



```{r}
saveRDS(cl0, paste0(dir,"/cl0.RDS"))
saveRDS(cl01, paste0(dir,"/cl01.RDS"))
saveRDS(cl1, paste0(dir,"/cl1.RDS"))
saveRDS(cl2, paste0(dir,"/cl2.RDS"))
saveRDS(cl3, paste0(dir,"/cl3.RDS"))
saveRDS(cl4, paste0(dir,"/cl4.RDS"))
saveRDS(cl5, paste0(dir,"/cl5.RDS"))
saveRDS(cl6, paste0(dir,"/cl6.RDS"))
saveRDS(cl7, paste0(dir,"/cl7.RDS"))
saveRDS(cl8, paste0(dir,"/cl8.RDS"))

cl0  <- readRDS("Results/Comparison WT-IRF8/cl0.RDS")
cl01  <- readRDS("Results/Comparison WT-IRF8/cl01.RDS")
cl1  <- readRDS("Results/Comparison WT-IRF8/cl1.RDS")
cl2  <- readRDS("Results/Comparison WT-IRF8/cl2.RDS")
cl3  <- readRDS("Results/Comparison WT-IRF8/cl3.RDS")
cl4  <- readRDS("Results/Comparison WT-IRF8/cl4.RDS")
cl5  <- readRDS("Results/Comparison WT-IRF8/cl5.RDS")
cl6  <- readRDS("Results/Comparison WT-IRF8/cl6.RDS")
cl7  <- readRDS("Results/Comparison WT-IRF8/cl7.RDS")
cl8  <- readRDS("Results/Comparison WT-IRF8/cl8.RDS")
```


```{r}
#cluster 0
eg = bitr(rownames(cl0), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl0 <- merge(cl0, eg, by = "row.names")
rownames(diffexpgenes.cl0) <- diffexpgenes.cl0$Row.names
diffexpgenes.cl0$Row.names <- NULL

fc <- diffexpgenes.cl0$avg_log2FC
names(fc) <- diffexpgenes.cl0$ENTREZID
fc <- sort(fc, decreasing = T)

gse0<-gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse0@result

dotplot(gse0, showCategory=30, split=".sign", font=8, title="Cluster 0") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl0.png"), height=9, width=5, dpi=600)

GO0 <- gse0@result$Description
head(GO0, 100)
write.csv2(gse0, "Results/Comparison WT-IRF8/gse/gse0.csv")

dotplot(gse0, showCategory=c("innate immune response", "immune effector process", "antigen processing and presentation of peptide antigen"), split=".sign", font=14, title="0 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#8AB6F9"))
ggsave(paste0(dir,"/GSEAdot.select.cl0.png"), height=2.3, width=6.6, dpi=600)
```

```{r}
#cluster 01
eg = bitr(rownames(cl01), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl01 <- merge(cl01, eg, by = "row.names")
rownames(diffexpgenes.cl01) <- diffexpgenes.cl01$Row.names
diffexpgenes.cl01$Row.names <- NULL

fc <- diffexpgenes.cl01$avg_log2FC
names(fc) <- diffexpgenes.cl01$ENTREZID
fc <- sort(fc, decreasing = T)

gse01 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse01@result

dotplot(gse01, showCategory=30, split=".sign", font=8, title="Cluster 0+1") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl01.png"), height=9, width=5, dpi=600)

GO01 <- gse01@result$Description
head(GO01, 100)
write.csv2(gse01, "Results/Comparison WT-IRF8/gse/gse01.csv")

g01<- dotplot(gse01, showCategory=c("ribosome biogenesis", "protein polymerization", "cellular lipid metabolic process", "immune effector process", "innate immune response"), split=".sign", font=14, title="0+1 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#8AB6F9"))
g01
ggsave(paste0(dir,"/GSEAdot.select.cl01.png"), height=3, width=6.6, dpi=600)


```


```{r}
#cluster 1
eg = bitr(rownames(cl1), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl1 <- merge(cl1, eg, by = "row.names")
rownames(diffexpgenes.cl1) <- diffexpgenes.cl1$Row.names
diffexpgenes.cl1$Row.names <- NULL

fc <- diffexpgenes.cl1$avg_log2FC
names(fc) <- diffexpgenes.cl1$ENTREZID
fc <- sort(fc, decreasing = T)

gse1 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800,  OrgDb = "org.Mm.eg.db", seed=1)
res <- gse1@result

dotplot(gse1, showCategory=30, split=".sign", font=8, title="Cluster 1") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl1.png"), height=9, width=5, dpi=600)

GO1 <- gse1@result$Description
head(GO1, 100)
write.csv2(gse1, "Results/Comparison WT-IRF8/gse/gse1.csv")

g1<- dotplot(gse1, showCategory=c("regulation of interleukin-1 beta production", "fatty acid metabolic process", "interleukin-6 production", "immune effector process", "mononuclear cell differentiation", "ribosome biogenesis", "cytoplasmic translation"), split=".sign", font=14, title="1 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#B25690"))
g1
ggsave(paste0(dir,"/GSEAdot.select.cl1.png"), height=3.5, width=6.6, dpi=600)
```

```{r}
#cluster 2
eg = bitr(rownames(cl2), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl2 <- merge(cl2, eg, by = "row.names")
rownames(diffexpgenes.cl2) <- diffexpgenes.cl2$Row.names
diffexpgenes.cl2$Row.names <- NULL

fc <- diffexpgenes.cl2$avg_log2FC
names(fc) <- diffexpgenes.cl2$ENTREZID
fc <- sort(fc, decreasing = T)

gse2 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse2@result

dotplot(gse2, showCategory=30, split=".sign", font=8, title="Cluster 2") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl2.png"), height=9, width=5, dpi=600)

GO2 <- gse2@result$Description
head(GO2, 100)
write.csv2(gse2, "Results/Comparison WT-IRF8/gse/gse2.csv")

g2<- dotplot(gse2, showCategory=c("ribosome biogenesis", "cytoplasmic translation", "prostaglandin metabolic process", "fatty acid transport", "interleukin-6 production", "mononuclear cell differentiation"), split=".sign", font=14, title="2 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#ffc13b"))
g2
ggsave(paste0(dir,"/GSEAdot.select.cl2.png"), height=3.3, width=6.6, dpi=600)
```

```{r}
#cluster 3
eg = bitr(rownames(cl3), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl3 <- merge(cl3, eg, by = "row.names")
rownames(diffexpgenes.cl3) <- diffexpgenes.cl3$Row.names
diffexpgenes.cl3$Row.names <- NULL

fc <- diffexpgenes.cl3$avg_log2FC
names(fc) <- diffexpgenes.cl3$ENTREZID
fc <- sort(fc, decreasing = T)

gse3 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse3@result

dotplot(gse3, showCategory=30, split=".sign", font=8, title="Cluster 3") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl3.png"), height=9, width=5, dpi=600)

GO3 <- gse3@result$Description
head(GO3, 100)
write.csv2(gse3, "Results/Comparison WT-IRF8/gse/gse3.csv")

g3<- dotplot(gse3, showCategory=c("negative regulation of immune system process", "positive regulation of protein-containing complex assembly"), split=".sign", font=14, title="3 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#04d4f0"))
g3
ggsave(paste0(dir,"/GSEAdot.select.cl3.png"), height=3.2, width=6.6, dpi=600)

```

```{r}
#cluster 4
eg = bitr(rownames(cl4), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl4 <- merge(cl4, eg, by = "row.names")
rownames(diffexpgenes.cl4) <- diffexpgenes.cl4$Row.names
diffexpgenes.cl4$Row.names <- NULL

fc <- diffexpgenes.cl4$avg_log2FC
names(fc) <- diffexpgenes.cl4$ENTREZID
fc <- sort(fc, decreasing = T)

gse4 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse4@result

dotplot(gse4, showCategory=30, split=".sign", font=8, title="Cluster 4") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl4.png"), height=9, width=5, dpi=600)

GO4 <- gse4@result$Description
head(GO4, 100)
write.csv2(gse4, "Results/Comparison WT-IRF8/gse/gse4.csv")

g4<- dotplot(gse4, showCategory=c("ribonucleoprotein complex biogenesis", "response to external stimulus", "positive regulation of RNA metabolic process", "ERK1 and ERK2 cascade"), split=".sign", font=14, title="4 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#5c3c92"))
g4
ggsave(paste0(dir,"/GSEAdot.select.cl4.png"), height=3.2, width=6.6, dpi=600)
```


```{r}
#cluster 5
eg = bitr(rownames(cl5), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl5 <- merge(cl5, eg, by = "row.names")
rownames(diffexpgenes.cl5) <- diffexpgenes.cl5$Row.names
diffexpgenes.cl5$Row.names <- NULL

fc <- diffexpgenes.cl5$avg_log2FC
names(fc) <- diffexpgenes.cl5$ENTREZID
fc <- sort(fc, decreasing = T)

gse5 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse5@result

dotplot(gse5, showCategory=30, split=".sign", font=8, title="Cluster 5") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl5.png"), height=9, width=5, dpi=600)

GO5 <- gse5@result$Description
head(GO5, 100)
write.csv2(gse5, "Results/Comparison WT-IRF8/gse/gse5.csv")

g5<- dotplot(gse5, showCategory=c("cytoplasmic translation", "cell differentiation", "inflammatory response", "tumor necrosis factor production", "interleukin-6 production", "interferon-gamma production"), split=".sign", font=14, title="5 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#077b8a"))
g5
ggsave(paste0(dir,"/GSEAdot.select.cl5.png"), height=3.2, width=6.6, dpi=600)
```


```{r}
#cluster 6
eg = bitr(rownames(cl6), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl6 <- merge(cl6, eg, by = "row.names")
rownames(diffexpgenes.cl6) <- diffexpgenes.cl6$Row.names
diffexpgenes.cl6$Row.names <- NULL

fc <- diffexpgenes.cl6$avg_log2FC
names(fc) <- diffexpgenes.cl6$ENTREZID
fc <- sort(fc, decreasing = T)

gse6 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse6@result

dotplot(gse6, showCategory=30, split=".sign", font=8, title="Cluster 6") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl6.png"), height=9, width=5, dpi=600)

GO6 <- gse6@result$Description
head(GO6, 100)
write.csv2(gse6, "Results/Comparison WT-IRF8/gse/gse6.csv")

g6<- dotplot(gse6, showCategory=c("response to tumor necrosis factor", "cell population proliferation", "antigen processing and presentation of peptide antigen", "tumor necrosis factor production", "innate immune response"), split=".sign", font=14, title="6 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#d72631"))
g6
ggsave(paste0(dir,"/GSEAdot.select.cl6.png"), height=3.2, width=6.6, dpi=600)
```


```{r}
#cluster 7
eg = bitr(rownames(cl7), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl7 <- merge(cl7, eg, by = "row.names")
rownames(diffexpgenes.cl7) <- diffexpgenes.cl7$Row.names
diffexpgenes.cl7$Row.names <- NULL

fc <- diffexpgenes.cl7$avg_log2FC
names(fc) <- diffexpgenes.cl7$ENTREZID
fc <- sort(fc, decreasing = T)

gse7 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse7@result

dotplot(gse7, showCategory=30, split=".sign", font=8, title="Cluster 7") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl7.png"), height=9, width=5, dpi=600)

GO7 <- gse7@result$Description
head(GO7, 100)
write.csv2(gse7, "Results/Comparison WT-IRF8/gse/gse7.csv")

g7<- dotplot(gse7, showCategory=c("rRNA processing", "aerobic respiration", "regulation of metabolic process", "immune system process", "regulation of chemokine production", "regulation of nitric-oxide synthase activity"), split=".sign", font=14, title="7 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#c38b72"))
g7
ggsave(paste0(dir,"/GSEAdot.select.cl7.png"), height=3.5, width=6.6, dpi=600)
```

```{r}
#cluster 8
eg = bitr(rownames(cl8), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
eg <- subset(eg,!duplicated(eg$SYMBOL))
row.names(eg) <- eg$SYMBOL
eg$SYMBOL <- NULL
diffexpgenes.cl8 <- merge(cl8, eg, by = "row.names")
rownames(diffexpgenes.cl8) <- diffexpgenes.cl8$Row.names
diffexpgenes.cl8$Row.names <- NULL

fc <- diffexpgenes.cl8$avg_log2FC
names(fc) <- diffexpgenes.cl8$ENTREZID
fc <- sort(fc, decreasing = T)

gse8 <- gseGO(geneList=fc, minGSSize = 5, maxGSSize = 800, OrgDb = "org.Mm.eg.db", seed=1)
res <- gse8@result

dotplot(gse8, showCategory=30, split=".sign", font=8, title="Cluster 8") + facet_grid(.~.sign)
ggsave(paste0(dir,"/GSEAdot.cl8.png"), height=9, width=5, dpi=600)

GO8 <- gse8@result$Description
head(GO8, 100)
write.csv2(gse8, "Results/Comparison WT-IRF8/gse/gse8.csv")

g8<- dotplot(gse8, showCategory=c("response to interleukin-1", "response to chemokine", "response to tumor necrosis factor", "immune response", "MHC class II protein complex assembly", "defense response to bacterium"), split=".sign", font=14, title="8 - IRF8ko vs. WT") + facet_grid(.~.sign)+ scale_colour_gradientn(colours = c("red4", "cornflowerblue"))+theme(plot.title= element_text(size=19, colour = "#80c904"))
g8
ggsave(paste0(dir,"/GSEAdot.select.cl8.png"), height=3.5, width=6.6, dpi=600)
```


```{r}
plot_grid(g01, g5, g6, ncol = 1, align="v")
ggsave(paste0(dir,"/01-5-6.png"), height=8, width=6, dpi=600)
```






